package shuhai.readercore.view.readview.status;
/**
 * @author 55345364
 * @date 2017/7/6.
 */

public enum BookStatus {

    NO_PRE_PAGE,
    NO_CUR_PAGE,
    NO_NEXT_PAGE,


    PRE_CHAPTER_LOAD_SUCCESS,
    PRE_CHAPTER_LOAD_FAILURE,

    CUR_CHAPTER_LOAD_FAILURE,
    CUR_CHAPTER_LOAD_SUCCESS,

    NEXT_CHAPTER_LOAD_FAILURE,
    NEXT_CHAPTER_LOAD_SUCCESS,

    LOAD_START,
    LOAD_COMPLETE,
    LOAD_SUCCESS,
    LOAD_ERROR,
    LOAD_NET_WORT_ERROR,
    NEED_BUY_CHAPTER


}
