package shuhai.readercore.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "BOOK_INFO_ENTITY".
 */
public class BookInfoEntity {

    private long articleid;
    private String articlename;
    private String author;
    private String bkbmurl;
    private Integer endtype;
    private String newchpname;
    private String owner;
    private Integer readtime;
    private Integer lastreadchporder;
    private Integer bktype;
    private Integer newchporder;

    public BookInfoEntity() {
    }

    public BookInfoEntity(long articleid) {
        this.articleid = articleid;
    }

    public BookInfoEntity(long articleid, String articlename, String author, String bkbmurl, Integer endtype, String newchpname, String owner, Integer readtime, Integer lastreadchporder, Integer bktype, Integer newchporder) {
        this.articleid = articleid;
        this.articlename = articlename;
        this.author = author;
        this.bkbmurl = bkbmurl;
        this.endtype = endtype;
        this.newchpname = newchpname;
        this.owner = owner;
        this.readtime = readtime;
        this.lastreadchporder = lastreadchporder;
        this.bktype = bktype;
        this.newchporder = newchporder;
    }

    public long getArticleid() {
        return articleid;
    }

    public void setArticleid(long articleid) {
        this.articleid = articleid;
    }

    public String getArticlename() {
        return articlename;
    }

    public void setArticlename(String articlename) {
        this.articlename = articlename;
    }

    public String getAuthor() {
        return author;
    }

    public void setAuthor(String author) {
        this.author = author;
    }

    public String getBkbmurl() {
        return bkbmurl;
    }

    public void setBkbmurl(String bkbmurl) {
        this.bkbmurl = bkbmurl;
    }

    public Integer getEndtype() {
        return endtype;
    }

    public void setEndtype(Integer endtype) {
        this.endtype = endtype;
    }

    public String getNewchpname() {
        return newchpname;
    }

    public void setNewchpname(String newchpname) {
        this.newchpname = newchpname;
    }

    public String getOwner() {
        return owner;
    }

    public void setOwner(String owner) {
        this.owner = owner;
    }

    public Integer getReadtime() {
        return readtime;
    }

    public void setReadtime(Integer readtime) {
        this.readtime = readtime;
    }

    public Integer getLastreadchporder() {
        return lastreadchporder;
    }

    public void setLastreadchporder(Integer lastreadchporder) {
        this.lastreadchporder = lastreadchporder;
    }

    public Integer getBktype() {
        return bktype;
    }

    public void setBktype(Integer bktype) {
        this.bktype = bktype;
    }

    public Integer getNewchporder() {
        return newchporder;
    }

    public void setNewchporder(Integer newchporder) {
        this.newchporder = newchporder;
    }

}
