package shuhai.readercore.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "CHAPTER_ENTITY".
 */
public class ChapterEntity {

    private Integer articleid;
    private long chpid;
    private String chpnamme;
    private Integer chptype;
    private Integer chiporder;

    public ChapterEntity() {
    }

    public ChapterEntity(long chpid) {
        this.chpid = chpid;
    }

    public ChapterEntity(Integer articleid, long chpid, String chpnamme, Integer chptype, Integer chiporder) {
        this.articleid = articleid;
        this.chpid = chpid;
        this.chpnamme = chpnamme;
        this.chptype = chptype;
        this.chiporder = chiporder;
    }

    public Integer getArticleid() {
        return articleid;
    }

    public void setArticleid(Integer articleid) {
        this.articleid = articleid;
    }

    public long getChpid() {
        return chpid;
    }

    public void setChpid(long chpid) {
        this.chpid = chpid;
    }

    public String getChpnamme() {
        return chpnamme;
    }

    public void setChpnamme(String chpnamme) {
        this.chpnamme = chpnamme;
    }

    public Integer getChptype() {
        return chptype;
    }

    public void setChptype(Integer chptype) {
        this.chptype = chptype;
    }

    public Integer getChiporder() {
        return chiporder;
    }

    public void setChiporder(Integer chiporder) {
        this.chiporder = chiporder;
    }

}
