package shuhai.readercore.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import shuhai.readercore.dao.BookInfoEntity;
import shuhai.readercore.dao.ChapterEntity;
import shuhai.readercore.dao.MarkEntity;

import shuhai.readercore.dao.BookInfoEntityDao;
import shuhai.readercore.dao.ChapterEntityDao;
import shuhai.readercore.dao.MarkEntityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig bookInfoEntityDaoConfig;
    private final DaoConfig chapterEntityDaoConfig;
    private final DaoConfig markEntityDaoConfig;

    private final BookInfoEntityDao bookInfoEntityDao;
    private final ChapterEntityDao chapterEntityDao;
    private final MarkEntityDao markEntityDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        bookInfoEntityDaoConfig = daoConfigMap.get(BookInfoEntityDao.class).clone();
        bookInfoEntityDaoConfig.initIdentityScope(type);

        chapterEntityDaoConfig = daoConfigMap.get(ChapterEntityDao.class).clone();
        chapterEntityDaoConfig.initIdentityScope(type);

        markEntityDaoConfig = daoConfigMap.get(MarkEntityDao.class).clone();
        markEntityDaoConfig.initIdentityScope(type);

        bookInfoEntityDao = new BookInfoEntityDao(bookInfoEntityDaoConfig, this);
        chapterEntityDao = new ChapterEntityDao(chapterEntityDaoConfig, this);
        markEntityDao = new MarkEntityDao(markEntityDaoConfig, this);

        registerDao(BookInfoEntity.class, bookInfoEntityDao);
        registerDao(ChapterEntity.class, chapterEntityDao);
        registerDao(MarkEntity.class, markEntityDao);
    }
    
    public void clear() {
        bookInfoEntityDaoConfig.getIdentityScope().clear();
        chapterEntityDaoConfig.getIdentityScope().clear();
        markEntityDaoConfig.getIdentityScope().clear();
    }

    public BookInfoEntityDao getBookInfoEntityDao() {
        return bookInfoEntityDao;
    }

    public ChapterEntityDao getChapterEntityDao() {
        return chapterEntityDao;
    }

    public MarkEntityDao getMarkEntityDao() {
        return markEntityDao;
    }

}
